version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbcrud
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1             # banco sempre 1 réplica
      placement:
        constraints: [node.role == manager]

  web:
    image: docker-project-web:latest
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: dbcrud
    ports:
      - "5000:5000"            # published port do swarm
    deploy:
      replicas: 2              # AGORA VAI ter 2 réplicas
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  mysql_data:
