version: '3.8'

services:

  db:
    image: mysql:8.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbcrud
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: docker-project-web   # <-- troque pela SUA imagem do Docker Hub
    deploy:
      replicas: 2  # demonstração de DR
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST=db
      MYSQL_PORT=3306
      MYSQL_USER=root
      MYSQL_PASSWORD=root
      MYSQL_DB=dbcrud

volumes:
  mysql_data:
